docs/tutorials/search-granules.md
Hi @betolink et al, I believe this was a typo in the How To documentation!
=> fix typo - comma, not a `

earthaccess/store.py, tests/unit/test_store.py
Closes https://github.com/nsidc/earthaccess/issues/248
cc @betolink
=> Raise informative error without inputs to `get_s3fs_session`

earthaccess/api.py
Copy and pasting this example as is gives me the following error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[50], line 1
----> 1 datasets = earthaccess.search_datasets(
2     keywords="sea surface anomaly",
3     cloud_hosted=True
4 )
File ~/mambaforge/envs/earthaccess/lib/python3.9/site-packages/earthaccess/api.py:57, in search_datasets(count, **kwargs)
53     print(
54         "Warning: a valid set of parameters is needed to search for datasets on CMR"
55     )
56     return []
---> 57 query = DataCollections().parameters(**kwargs)
58 datasets_found = query.hits()
59 print(f"Datasets found: {datasets_found}")
File …
```
=> Update example in `search_datasets`

.github/workflows/documentation.yml
This PR makes it so the docs are only deployed on pushes to the `main` branch of `nsidc/earthaccess`
cc @betolink 
xref https://github.com/nsidc/earthaccess/pull/260
=> Limit documentation deployment

earthaccess/api.py
This PR address #262.
Following the api workflow in the readme, if `earthaccess.login()` is not executed before download, download fails with an ambiguous `AttributeError`.  To fix this, I added a `try-except` block to `download` in `api.py`, so that the user is advised to run `earthdata.login()` before attempting to download and `None` is returned.
=> add try block to return useful error message for failed download

docs/tutorials/onprem.md
Added howto for download from on-prem.
I'm not sure how to test or build the documentation locally.
=> add download from onprem how-to

earthaccess/api.py, earthaccess/store.py
This PR adds an `fsspec`-compatible `EarthAccessFile` object that's a very light wrapper around the current https / S3 file objects being used. The only difference is that when a file is serialized (as happens when working on a remote cluster), if we find that we are running in region on AWS and the underlying file is an https file instead of an S3 file, we reopen the file using the existing `eathaccess.open(...)` logic to get a S3 file. 
Anecdotally, I see a computation performance boost of 2x when running the notebook in https://github.com/nsidc/earthaccess/issues/253 with the changes in this PR 
Closes https://github.com/nsidc/earthaccess/issues/253
=> Improved remote cluster performance

.github/workflows/documentation.yml, .github/workflows/integration-test.yml, CHANGELOG.md, README.md, docs/CONTRIBUTING.md, docs/tutorials/authenticate.md, docs/tutorials/file-access.ipynb, docs/tutorials/queries.ipynb, docs/tutorials/restricted-datasets.ipynb, earthaccess/api.py, earthaccess/formatters.py, earthaccess/results.py, earthaccess/search.py, earthaccess/store.py, mkdocs.yml, pyproject.toml, scripts/docs-live.sh, scripts/integration-test.sh, scripts/test.sh, tests/integration/test_onprem_download.py, tests/integration/test_onprem_open.py
Features:
* we can search by doi at the granule level, if a collection is found `earthaccess` will grab the `concept_id` and search using it.
* users will be able to use pattern matching on the granule file names!
* README is now using the SSHA dataset from PODAAC as is simpler to explain and work with compared to ATL data, closes #241
* The granule representation removed the spatial output in favor of a simpler is_cloud_hosted until we have a nicer spatial formatter (it was a blob of json)
Bug fixes:
* size() now returns the actual size closes #233
Documentation:
* using earthdata.login() instead of a specific strategy, addresses #218 
CI:
* integration tests are only going to run on pushes to main
* documentation is only going to be updated when we update main
TODO:
* documentation …
=> Search improvements

earthaccess/api.py, earthaccess/store.py
With https://github.com/nsidc/earthaccess/pull/259, when serializing files, we started re-checking the filesystem type (HTTPS vs. S3) and, if we are on AWS but not using S3 files, we now re-open the file using an `s3fs` filesystem.
This is good for performance, but when running on a remote Dask cluster, users now need to have all nodes in their cluster (i.e. client, scheduler, and workers) authenticated with `earthaccess`. For example, if only the client session is authenticated, like in this example:
```python
import earthaccess
from distributed import SubprocessCluster
import xarray as xr
earthaccess.login()
cluster = SubprocessCluster()
client = cluster.get_client()
results = earthaccess.search_data(
short_name="VIIRS_NPP-STAR-L3U-v2.80",
concept_id="C2147485059-POCLOUD", …
```
=> Avoid auth error when serializing files across processes

tests/integration/test_api.py
`tests/integration/test_api.py::test_dataset_search_returns_valid_results` is failing on `main` with (e.g. see [this CI build](https://github.com/nsidc/earthaccess/actions/runs/6115023521/job/16597781359)): 
```
FAILED tests/integration/test_api.py::test_dataset_search_returns_valid_results[kwargs2] - IndexError: list index out of range
```
Changing the `daac` fixes the issue locally for me
=> Fix ``test_dataset_search_returns_valid_results`` integration test

earthaccess/api.py, earthaccess/auth.py, earthaccess/results.py, earthaccess/store.py, pyproject.toml, tests/unit/test_store.py
This PR allows `earthacces.search_data()` and `earthaccess.search_dataset()` use the `auth` object to send bearer tokens to CMR, usually this is not required but in the case of restricted datasets or early release data CMR will only return results if we are in the access control lists for a given dataset. 
with this PR `earthaccess` will be able to use the metadata from CMR to grab S3 credentials, perhaps we need to simplify this even more but for now this works.
```python
import earthaccess
earthaccess.login()
results = earthaccess.search_data(
short_name='SWOT_L2_HR_RIVERSP_1.0',
cloud_hosted=True,
bounding_box=(-10, 20, 10, 50),
temporal=("1999-02", "2019-03"),
count=10
)
earrthaccess.open(results)
```
This code was failing because the SWOT mission has its own S3 credentials that are …
=> Use CMR metadata to get S3FS sessions and authenticate queries to CMR using top level APIs

earthaccess/api.py, earthaccess/store.py
This PR update the ``EarthAccessFile`` pickle logic to handle the case that we're starting in region and sending a ``EarthAccessFile`` to a different process also in region. I had been testing the out of S3 to S3 code path when writing this code originally, but @betolink and I both ran into cases where this logic wasn't quite correct in other situations. I think this should now be correct.
=> Update ``EarthAccessFile`` serialization logic

CHANGELOG.md, earthaccess/store.py
Couple of minor fixups that I noticed while looking at `earthaccess.store`:
* Fixup spelling mistake in `access` variable assignment (`direc` -> `direct`)
* Pass `threads` arg to `_open_urls_https` in `_open_urls`, replacing hard-coded value of 8.
=> Small store fixups

earthaccess/api.py, earthaccess/store.py, tests/integration/test_api.py
This PR contains a few ergonomic updates to `earthaccess.download`. Specifically:
1. `earthaccess.download` now accepts a single granule as input in addition to a list of granules
2. The files returned by `earthaccess.download` are now the fully qualified local paths. This makes it easier to do things with the paths that are returned (currently there is some extra `os.path.join` that needs to happen)
```python
files = earthaccess.download(...)
for file in files:
with open(file) as f:
...
```
3. Technically `local_path` can be `None` when using `earthaccess.download`. We weren't accounting for that possibility in all the possible `download` cases (e.g. downloading from S3). This PR moves the `local_path=None` logic higher up in the call stack to account for these cases.
=> Minor `earthaccess.download` updates

earthaccess/__init__.py, earthaccess/api.py, tests/integration/test_api.py
When working with multiple machines, it's often easier to set authentication environment variables than it is to ship a `.netrc` file around. This PR adds a small utility for programmatically retrieving `EARTHDATA_USERNAME` and `EARTHDATA_PASSWORD`
=> Add utility for getting authentication environment variables

tests/integration/test_api.py
This is currently failing on `main` with `FAILED tests/integration/test_api.py::test_auth_environ_raises - Failed: DID NOT RAISE <class 'RuntimeError'>`  (for example, see [this CI build](https://github.com/nsidc/earthaccess/actions/runs/6538911512/job/17763073681)) due to the new automatic authentication update (xref https://github.com/nsidc/earthaccess/pull/300). 
This PR update this test accordingly so it passes while still keeping the original intent of the test
=> Fix ``test_auth_environ_raises integration`` test

earthaccess/results.py, tests/unit/test_results.py
I went to run the code referenced here https://github.com/nsidc/earthaccess/pull/316#issuecomment-1762014343 and got an error because it turns out `granule.data_links(access="direct", in_region=True)` returns a HTTPS link. This PR fixes that specific case and also makes it so `granule.data_links(in_region=True)` returns S3 links by default (which seems like it's the expected behavior, but @betolink @MattF-NSIDC let me know if you think otherwise).
I'm testing this PR out now to make sure if in fact fixes things
=> Return S3 data links by default when in region

CHANGELOG.md, CITATION.cff, CONTRIBUTING.md, pyproject.toml
Closes https://github.com/nsidc/earthaccess/issues/322
cc @betolink @MattF-NSIDC
=> Release 0.7.0

earthaccess/search.py
Resolves #338
We have a similar check in `results.py`: https://github.com/nsidc/earthaccess/blob/8461cfa1302d1186be88d5067c24531d5bde9be7/earthaccess/results.py#L51-L52
I'm going to want to release ASAP to support [Antarctica Today](https://github.com/nsidc/antarctica_today).
=> Fix: Assume granules without `RelatedUrls` are not cloud hosted

.github/workflows/test.yml, .pre-commit-config.yaml, mypy.ini, pyproject.toml, pytest.ini
Pytest and Mypy can both be configured by `pyproject.toml`. 
[Flake8 can't](https://github.com/PyCQA/flake8/issues/234), but Ruff can. I prefer Ruff anyway, so I opened #341.
=> Migrate tool configs to pyproject.toml, configure pre-commit.ci

earthaccess/store.py
There are a few places where we're currently printing a message and returning `None`, `[]`, etc. when something goes wrong. It's nice that there's typically an informative message, but it relatively easy to ignore these messages (guilty myself), and can lead to unexpected downstream errors (e.g. downstream code is expecting a list of strings, but you give it `None` instead).
Here's an example
```python
In [5]: result = earthaccess.open(["notavalidprotocol://myfile.nc"])
Schema for notavalidprotocol://myfile.nc is not recognized, must be an HTTP or S3 URL
In [6]: type(result)
Out[6]: NoneType
```
This PR proposes we raise exceptions in these cases (still with an informative message) to properly signal "Hey, something went wrong here". This should make it more clear where things are going …
=> Raise exceptions more

index.html
> [!IMPORTANT]
>
> Note that this PR targets the `new-gh-pages` branch. This is an orphan branch created with `git checkout --orphan new-gh-pages`. Then, an empty commit was created with `git commit --allow-empty`. Then, my feature branch was taken from this new HEAD. This simulates the nature of the `gh-pages` branch in a way that is reviewable. Once this PR is approved and merged, I'll replace the `gh-pages` branch with the contents of the `new-gh-pages` branch and squash to one commit. From then on, changes to `gh-pages` can be done with PRs.
This PR enables redirect to ReadTheDocs and decommissioning of the docs GitHub Action (see #277, #362).
Should there be a README on this branch? The `index.html` file is pretty self-explanatory.
=> Replace GitHub Pages documentation site with `index.html` that redirects to ReadTheDocs

.github/workflows/issue-manager.yml
We weren't using an "answered" label, so I just replaced it.
Triggers updated per documentation!
=> Update issue manager with "feedback requested" behavior

earthaccess/api.py, tests/integration/test_auth.py
I was just working with someone who got an error because they provider `provider="pocloud"` (lowercase) instead of `provider="POCLOUD"`. All our internal machinery expects `provider` and `daac` to be all uppercase, however it's pretty natural (especially for new users) to use lowercase instead. We should just handle this case by normalizing these inputs to be all uppercase. `earthaccess. get_s3_credentials` already had logic for this, but other methods didn't. This PR adds similar logic to other top-level `earthaccess` APIs.
=> Handle lowercase `daac` and `provider` inputs

earthaccess/api.py, tests/integration/test_api.py
Similar to https://github.com/nsidc/earthaccess/pull/317 but for a single `https://...` URL instead of a single data granule
=> Allow single file URL inputs for ``earthaccess.download``

.github/dependabot.yml
If anyone approves, please also merge :)
=> Roll up dependabot GHA updates into one PR

CHANGELOG.md, CITATION.cff, pyproject.toml
I couldn't get bump my version to work so I just updated things manually based on the changes in https://github.com/nsidc/earthaccess/pull/371
Closes https://github.com/nsidc/earthaccess/issues/387
=> Release 0.8.1

earthaccess/store.py, tests/integration/test_cloud_download.py, tests/integration/test_cloud_open.py
Marking as WIP as this doesn't handle all the open + download code paths yet and I think `mypy` isn't happy right now either. Just wanted to get a quick +1 for this general direction before finishing up. 
Closes https://github.com/nsidc/earthaccess/issues/393
=> Handle opening multi-file granules

CHANGELOG.md, earthaccess/store.py
Fixes #390 with a small change to the check for instance metadata query. For IMDSv2, the first request must be a PUT to "http://169.254.169.254/latest/api/token". A Response OK on that seems like a sufficient check.
Tests ... I would love to add a test. I have no idea how a test that depends on running on an EC2 instance could be set up. If you would like to provide guidance, happy to tackle.
=> Enable AWS check with IMDSv2

.github/workflows/integration-test.yml, .github/workflows/issue-manager.yml, .github/workflows/test.yml, .pre-commit-config.yaml, binder/environment-dev.yml, binder/environment.yml, mkdocs.yml
Closes https://github.com/nsidc/earthaccess/issues/364. I broke this into two commits, one which adds the pre-commit hook, and one which applies the formatting, to hopefully make reviewing a little easier. 
cc @mfisher87 @betolink @jhkennedy
=> Add YAML formatting (prettier)

pyproject.toml
Closes https://github.com/nsidc/earthaccess/issues/392
cc @mfisher87
=> Add `python-dateutil` as a direct dependency

.github/workflows/pr-rtd-link.yml
This improves accessibility by removing the need to know in advance where to find the ReadTheDocs link in the GitHub PR interface. 
See demo: https://github.com/mfisher87/earthaccess/pull/11 (the link doesn't work because RTD isn't set up for my fork ;) )
=> Add workflow to update PRs with docs preview link in description

binder/environment-dev.yml, earthaccess/api.py, earthaccess/auth.py, earthaccess/daac.py, earthaccess/kerchunk.py, earthaccess/results.py, earthaccess/search.py, earthaccess/store.py, scripts/docs-live.sh, tests/integration/test_kerchunk.py
Addresses #279, but does not resolve it. This work exposed and addresses a couple of concerns, but there are some still I think that need more work.
On the `main` branch,  there are some formatting errors that are causing key information to be omitted from the docs. It seems _really_ easy to make these mistakes, and Mkdocs doesn't complain about them! How can we protect ourselves?
* We could really use some linting rules that can catch docstrings that are not formatted properly in the Google style. Ruff has some docstring PEP linters, but I don't think that's enough here. Can Ruff lint for Google docstring style?
* We need to be very careful with line-continuation. Line continuation must be done with an indent or everything on the next line will be either omitted or misformatted. A better …
=> Clarify that temporal and bbox args must be tuples in docstrings, fix docstring formatting

CHANGELOG.md, README.md, binder/environment-dev.yml, earthaccess/auth.py, earthaccess/results.py, earthaccess/search.py, poetry.lock, tests/unit/test_auth.py
* Fixes #439 by implementing multiple trusted domains (ASF's) on top of NASA's URS
* This will fix downloading data behind ASF datapool but we still can't open them because aiohttp/fsspec do not support rebuilding the authorization headers on redirects. This should work now
* ```python
import earthaccess
earthaccess.login()
results = earthaccess.search_data(
short_name='OPERA_L2_RTC-S1_V1',
cloud_hosted=True,
bounding_box=(-117.33, 35.541, -117.880, 35.991),
temporal=("2023-10-01", "2023-10-15"),
count=50
)
files = earthaccess.download(results, "./data")
```
* Fixes #438 by using an authenticated session in `hits()` instead of calling parent's class `super()`
* Improves search by adding instrument and project to collection queries #427 
* ```python
collections = …
```
=> fixing searching for restricted datasets and accessing ASF on demand data from Opera

earthaccess/search.py, tests/unit/test_collection_queries.py, tests/unit/test_granule_queries.py
in the `DataGranules` docstring it's written that we can pass datetime object but this wasn't true (or at least it was giving me `not recognized`) 
----
📚 Documentation preview 📚: https://earthaccess--451.org.readthedocs.build/en/451/
=> allow datetime object to be provided for temporal queries

earthaccess/auth.py
By request of NASA, ASF has moved the NISAR distribution endpoint to <https://nisar.asf.earthdatacloud.nasa.gov/> and killed the endpoint listed in `auth.py`. 
Word on the street is that when NISAR collections do show up in CMR, they will have URLs pointing directly to this distribution endpoint instead of obscured by `datapool.asf.alasak.edu`, so we shouldn't need to list it here. 
If we do end up needing to list it here, I'd rather circle back once a public collection is in CMR.
----
📚 Documentation preview 📚: https://earthaccess--495.org.readthedocs.build/en/495/
=> Remove deprecated NISAR URL from auth.py

earthaccess/auth.py
This PR includes code that will also create a .urs_cookies and .dodsrc files when users persist their credentials to a .netrc file, and will copy the .dodsrc file based on the user operating system. It is based on code from this how-to, but adapted here to use pathlib: https://disc.gsfc.nasa.gov/information/howto?keywords=prerequisite&title=How%20to%20Generate%20Earthdata%20Prerequisite%20Files
I have tested this with poetry on both Linux/Windows, and it works great!
----
📚 Documentation preview 📚: https://earthaccess--492.org.readthedocs.build/en/492/
=> Add dodsrc and urs cookies files when creating netrc

.github/workflows/integration-test.yml, .github/workflows/test-mindeps.yml
The concurrency groups for both integration-tests and test-mindeps were named the same, creating a race condition such that whichever workflow was started first would be cancelled by the start of the second workflow. This fix gives them distinct group names to avoid erroneously cancelling one or the other.
Fixes #503
----
📚 Documentation preview 📚: https://earthaccess--505.org.readthedocs.build/en/505/
=> Fix erroneous workflow cancellation

earthaccess/daac.py, tests/unit/test_collection_queries.py, tests/unit/test_store.py
OB.DAAC is joining the PARTY!
----
📚 Documentation preview 📚: https://earthaccess--516.org.readthedocs.build/en/516/
=> add obdaac s3-credential endpoint

docs/welcome/work_with_us.md, docs/work-with-us.md, mkdocs.yml
Right now, our announcement thread is the best place to link folks to learn about hack days. A permanent page in our docs is probably more useful! As we change our ways of collaborating with the public, e.g. transitioning to office hours?, we could update this page.
=> Add content about hack days to our docs

README.md, docs/index.md
Supersedes #534 .
The problem is that GitHub and Mkdocs use different syntax and have a different root directory, so symlinking files from the root directory isn't working as we expect it to work.
----
📚 Documentation preview 📚: https://earthaccess--541.org.readthedocs.build/en/541/
=> Split the README into a GitHub README and separate Mkdocs doc page

README.md, docs/quick-start.md, docs/user_guide/index.md, mkdocs.yml
TODO
----
📚 Documentation preview 📚: https://earthaccess--542.org.readthedocs.build/en/542/
=> Enable mkdocs strict mode to catch broken links

README.md
https://earthaccess.readthedocs.io/en/latest/quick-start/  had `.html` appended - I just updated with the correct link.
----
📚 Documentation preview 📚: https://earthaccess--560.org.readthedocs.build/en/560/
=> Fix broken quick start link

CHANGELOG.md, earthaccess/store.py
I didn't add a unit or integration test for this, as I wasn't sure about how best to test this, so I'm open to suggestion.
Fixes #562
----
📚 Documentation preview 📚: https://earthaccess--570.org.readthedocs.build/en/570/
=> Create dest dir for direct S3 access before download

.gitignore, .pre-commit-config.yaml, .yamlfmt.yml, CHANGELOG.md, mkdocs.yml
Fixes #555
----
📚 Documentation preview 📚: https://earthaccess--568.org.readthedocs.build/en/568/
=> Use yamlfmt instead of prettier to format YAML

CHANGELOG.md, earthaccess/api.py, earthaccess/auth.py, earthaccess/search.py, earthaccess/store.py, pyproject.toml, tests/integration/test_auth.py, tests/unit/test_auth.py
Addresses https://github.com/nsidc/earthaccess/issues/511
----
📚 Documentation preview 📚: https://earthaccess--566.org.readthedocs.build/en/566/
=> Replace print statements with logger

README.md
Resolves #561 
I have made the necessary changes. Please have a look at it;)
=> Add missing details to README

.github/workflows/issue-metrics.yml
We discussed this on a call today, since this may be useful we can run it manually with the "workflow_dispatch" option.
cc @asteiker @JessicaS11 @jhkennedy @andypbarrett @betolink 
----
📚 Documentation preview 📚: https://earthaccess--587.org.readthedocs.build/en/587/
=> Add GitHub issue metrics automation

.github/workflows/integration-test.yml, .github/workflows/test-mindeps.yml, .github/workflows/test.yml, CHANGELOG.md, ci/environment-mindeps.yaml, poetry.lock, pyproject.toml
Fixes #457
----
📚 Documentation preview 📚: https://earthaccess--571.org.readthedocs.build/en/571/
=> Add Python 3.12 to automated test matrix

earthaccess/__init__.py, earthaccess/api.py, earthaccess/auth.py, earthaccess/formatters.py, earthaccess/results.py, earthaccess/search.py, pyproject.toml, tests/integration/test_cloud_download.py, tests/integration/test_cloud_open.py, tests/integration/test_onprem_download.py, tests/integration/test_onprem_open.py, tests/unit/test_results.py
I have added the linting for docstrings. Please have a look at it ;) Resolves #454 
----
📚 Documentation preview 📚: https://earthaccess--580.org.readthedocs.build/en/580/
=> Added linting of docstrings

earthaccess/auth.py, earthaccess/search.py, earthaccess/store.py
I've done the changes as discussed. Please have a look at it ;). Closes #590
----
📚 Documentation preview 📚: https://earthaccess--596.org.readthedocs.build/en/596/
=> Did the necessary docstring cleanup as discussed in #590

earthaccess/daac.py
Closes #564.
The bug does not appear to be that "OBDAAC" is missing from `earthaccess.daac.CLOUD_PROVIDERS`. Rather, the issue seems to be that this list exists without having any function. The `CLOUD_PROVIDERS` list is not referenced in the project (according to VS Code and text search) and deleting it breaks no tests. This PR removes the cruft and does nothing else.
Please close without merging if you're aware of any purpose for this variable.
As far as adding OBDAAC goes, I think it was added correctly in #516.
----
📚 Documentation preview 📚: https://earthaccess--603.org.readthedocs.build/en/603/
=> remove the unreferenced `CLOUD_PROVIDERS` list

pyproject.toml
A colleague, and frequent `earthaccess` user, just said they did not know about https://earthaccess.readthedocs.io. Maybe adding the "documentation" URL will help this resource percolate through. Also changed "homepage" to the more specific "repository" (gets an octocat on PyPI).
----
📚 Documentation preview 📚: https://earthaccess--607.org.readthedocs.build/en/607/
=> Improve PyPI sidebar URLs

docs/howto/edl.ipynb
Moving s3credential guidance into markdown for security reasons. This will remove expired aws keys from the notebook.
----
📚 Documentation preview 📚: https://earthaccess--745.org.readthedocs.build/en/745/
=> Key removal

CHANGELOG.md, docs/contributing/maintainers-guide.md, docs/tutorials/SSL.ipynb
Updates the broken image link and a few typos in the sea level rise tutorial.
Closes https://github.com/nsidc/earthaccess/issues/427
----
📚 Documentation preview 📚: https://earthaccess--753.org.readthedocs.build/en/753/
=> 427: Fix broken image link in sea level rise tutorial

.github/pull_request_template.md, CHANGELOG.md, docs/contributing/index.md, docs/contributing/maintainers-guide.md
Addresses #281 but doesn't resolve it. We still need issue templates. We should break that ticket in to pieces.
cc @Sherwin-14 
----
📚 Documentation preview 📚: https://earthaccess--613.org.readthedocs.build/en/613/
=> Initial PR template

earthaccess/api.py, earthaccess/store.py, pyproject.toml, scripts/integration-test.sh, tests/integration/conftest.py
Resolves #737
I don't have free time to debug the actual failures. Just getting the tests to fail loudly was a headache :laughing: At a glance, I see a couple problems:
* We have some assertions at the module level that look like they should be set up in fixtures
* We're using unittest assert functions, so pytest is providing very poor error messages
=> Enable integration test workflow to better communicate failure

tests/integration/test_auth.py
I refactored the loop in here. I could only find this one to be refactored. What more could be done here?
----
📚 Documentation preview 📚: https://earthaccess--736.org.readthedocs.build/en/736/
=> Refactored the loop in the tests by parameterizing 

docs/user_guide/access.md, docs/user_guide/authenticate.md, docs/user_guide/search.md
Fixes a couple of broken links that I came across while browsing the `earthaccess` documentation. Resolves https://github.com/nsidc/earthaccess/issues/778
[Common Changelog](https://common-changelog.org/) for your …
=> Fixup broken links in docs

CHANGELOG.md, earthaccess/auth.py, tests/unit/test_auth.py, tests/unit/test_deprecations.py, tests/unit/test_store.py, tests/unit/test_uat.py
Like discussed in in #484 this simplifies authentication by using the `find_or_create_token`-endpoint and removing all other auth-endpoints. If all is good users should not notice this change besides when their tokens expire, then they should now just be re-created (I couldn't test that because I had no expired tokens available for testing that).
`auth.refresh_token()` has been deprecated.
Closes #484
Fixes #764 
- Links to any issues resolved by this PR with text in …
=> Change auth strategy to using find_or_create_token endpoint

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, CHANGELOG.md
I have added issue templates . Please have a look into it
----
📚 Documentation preview 📚: https://earthaccess--787.org.readthedocs.build/en/787/
=> Added Issue Templates

docs/contributing/development.md
Woops! Excellent catch @itcarroll 
----
📚 Documentation preview 📚: https://earthaccess--814.org.readthedocs.build/en/814/
=> Quote the pip install specification in development docs

.github/pull_request_template.md, CHANGELOG.md
I added the link's where I think my PR stands out as an example . Solves #756 
----
📚 Documentation preview 📚: https://earthaccess--820.org.readthedocs.build/en/820/
=> Added PR examples to Pull Request Template

.github/actions/install-pkg/action.yml, .github/workflows/integration-test.yml, .github/workflows/test.yml, .gitignore, docs/contributing/development.md, environment.yml, noxfile.py
This PR fixes the problem of failing integration tests on PRs from forked repos by allowing maintainers to review such PRs for potential security issues (which should be minimal for trusted/known contributors) and then re-running the failed jobs such that they may successfully run.
The result is the following:
1. In the integration test job, the permissions of the user (actor) triggering the PR are checked. If the user does not have write access to this repo, the job is immediately failed, thus avoiding any attempt to run integration tests, which would only fail anyway because without write permission, the secrets required by the integration tests cannot be read.
2. The job summary for the failed integration tests describe the problem (i.e., the triggering user does not have permission to …
=> Allow maintainers to run integration tests on PR from a fork

docs/user-reference/store/earthaccessfile.md, earthaccess/api.py, earthaccess/store.py, mkdocs.yml, tests/unit/test_store.py
A hackday quick fix with @nikki-t and @mfisher87 to undo the bad effects of #620. Conversation continues about the original bug report (#610).
What this PR does:
- adds the `fsspec.spec.AbstractBufferedFile` parent class (back) to `EarthAccessFile`
- marks the `test_earthaccess_file_getattr` test as expected fail because we re-introduce #610.
=> restore AbstractBaseClass inheritance

.github/pull_request_template.md, README.md, docs/contributing/development.md, docs/contributing/index.md, docs/contributing/maintainers-guide.md, docs/contributing/releasing.md, docs/quick-start.md, mkdocs.yml, noxfile.py, scripts/build-docs.sh, scripts/docs-live.sh
`earthaccess` documentation currently states that creating an issue is **required** before submitting a PR, which I think is an unnecessary barrier to many possible contributions. For example, it makes little sense to require an issue to fix a documentation spelling error. More discussion in slack here: https://openscapes.slack.com/archives/C05TMK269HA/p1726880090555649
I've:
* removed the " Ensure an issue exists representing the problem being solved in this PR." checklist item from our PR template
* added a "thank you" as the first thing potential contributors see when coming the contributing docs
* expanded the discussion of how to contribute
* reworked the different PR paths to be tabs instead of sections
* fixed a few typos
* updated `releasing.md` to exclusively use MkDocs style …
=> Update contributing guide to be more friendly

scripts/format.sh, scripts/verify_tag.sh
In this PR, I've:
* Removed `scripts/format.sh` as we currently don't document it and instead use Pre-Commit to run `ruff`
* Changed "Poetry" to "Pyproject.toml" in `scripts/verify_tag.sh` as we don't use poetry anymore.
I don't think either of these changes needs a changelog entry.
[GitHub docs - …
=> Drop unused format script

.github/workflows/issue-metrics.yml
Makes it so we can search for all the reports easily:
https://github.com/nsidc/earthaccess/issues?q=is%3Aissue+label%3Ametrics+
And that the specific date range of the report is clear.
[GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/li …
=> For our monthly issue metrics, Include the date range in the title and label "metrics"

.github/workflows/integration-test-review.yml, .yamlfmt.yml, CHANGELOG.md
Fixes #824
[Common Changelog](https://common-changelog.org/) for your …
=> Add PR comment when integration tests need review

CHANGELOG.md, earthaccess/search.py, tests/unit/fixtures/vcr_cassettes/TestResults.test_no_results.yaml, tests/unit/test_results.py
Currently, if you search for a collection that doesn't exist because you have the wrong name for it, `earthaccess` will bonk pretty hard with an error message that doesn't describe the problem:
```python
>>> import earthaccess
>>> earthaccess.login()
>>> results = earthaccess.search_data(
...     short_name='OPERA_L3_DSWX-HLS_V1_1.0',
...     bounding_box=(-95.19, 30.59, -94.99, 30.79),
...     temporal=('2024-04-30', '2024-05-31'),
... )
Traceback (most recent call last):
File ".../mambaforge/envs/earthaccess/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-2-7ebcf77bff69>", line 5, in <module>
results = earthaccess.search_data(
^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Only check if results are cloud hosted when there are results

CHANGELOG.md, earthaccess/api.py, earthaccess/store.py, tests/unit/test_api.py
I did all the steps outlined in the issue #581, we can now build upon this.
----
📚 Documentation preview 📚: https://earthaccess--792.org.readthedocs.build/en/792/
=> Added parameters and exception behaviour to pqdm

.github/workflows/integration-test.yml
=> Fix commit ref for integration tests workflow

.github/workflows/integration-test.yml
=> Do not run int tests on push

.github/workflows/issue-metrics.yml
Our monthly issue metrics GitHub Actions workflow is supposed to close the issue once created, but fails to do so:
https://github.com/nsidc/earthaccess/actions/runs/11623230080/job/32369942886#step:6:10
Failure was because we didn't specify the repo so it tried to base it on a local git repository, but there wasn't one because we don't need to check out the repository for the rest of the action steps.
I've updated the action to have  issue write permission (needed for the issue  PATCH API request)  as well as specifying the repo, which I confirm works in a directory with no git repository:
```
$ gh issue close 861 --reason "not planned" --repo nsidc/earthaccess
✓ Closed issue nsidc/earthaccess#861 (Monthly issue metrics report: 2024-10-01..2024-10-31)
```
I don't think there's much value …
=> Fix monthly issue metrics workflow

docs/tutorials/restricted-datasets.ipynb, notebooks/Demo.ipynb
This PR corrects two incorrect documentation hyperlinks to Earthdata Login.
----
📚 Documentation preview 📚: https://earthaccess--907.org.readthedocs.build/en/907/
=> Fix Incorrect Earthdata Login Hyperlinks

.github/workflows/discussions.yml, CHANGELOG.md
I have replaced the CATEGORY_ID and REPOSITORY_ID, though, it remains untested. (It would be funny if Github allowed me to open a discussions thread in another repository :laughing:)
----
📚 Documentation preview 📚: https://earthaccess--914.org.readthedocs.build/en/914/
=> Add a workflow for generating Hackday Github Discussion threads

CHANGELOG.md, earthaccess/store.py
Fixes #887 
The internals for download now use the recommended (by requests) `requests.Response.iter_content` method to download granules while keeping memory usage capped at 1MB.
[GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking …
=> download using chunk iteration rather than raw response

earthaccess/dmrpp_zarr.py, earthaccess/kerchunk.py, pyproject.toml, tests/integration/test_virtualizarr.py, uv.lock
----
📚 Documentation preview 📚: https://earthaccess--923.org.readthedocs.build/en/923/
=> Fix small open_virtual_dataset bugs

earthaccess/store.py, tests/unit/test_store.py
This pull request addresses a DSE issue reported by Earthdata Login (EDL) during data download requests involving large amount of granules through EarthAccess. One issue was traced to EarthAccess creating a new session for each download instead of reusing the existing session cookie, which is intended to reduce the number of requests to EDL by the DAAC data distribution endpoint (TEA). This PR introduces changes to enhance session cookie handling within each thread, avoiding EDL requests from TEA in subsequent authenticated data downloads.
Key modifications in this PR include:
- Thread-local Session Management: Added `_clone_session_in_local_thread` method to clone and store sessions in thread-local storage.
- Cookie Reuse in Downloads: Adapted `_download_file` method to utilize …
=> Thread-local Session Management and Cookie Reuse to Address EDL DSE issue

CHANGELOG.md, CITATION.cff, pyproject.toml
=> Preparing the release of v0.13.0

.pre-commit-config.yaml, uv.lock
pre-commit.ci fails because there is no internet access in that environment. They should fail based on the validity of uv.lock based on pyproject.toml. This introduces two versions of the hook, one offline and one online (manual).
Resolves #942 
[GitHub docs - Linking a pull request to an …
=> Do offline `uv-lock` check in CI, online check manually

CHANGELOG.md, earthaccess/api.py, earthaccess/search.py, tests/unit/test_collection_queries.py, uv.lock
Extend `search_datasets` API to allow a false value for `has_granules` when querying CMR. See https://github.com/nsidc/earthaccess/issues/939
- [X ] Please review our
- [X ] Populate a descriptive title. For example, instead of "Updated README.md", use a
- [X ] Populate the body of the pull request with:
example `closes #1`. …
=> Add option to search for collections without granules

.github/actions/install-pkg/action.yml, .github/workflows/integration-test.yml, .github/workflows/test-mindeps.yml, .github/workflows/test.yml, pyproject.toml, uv.lock
Use a separate cache for each python version matrix value.
[Common …
=> Fix tests' broken python version matrix

.github/workflows/integration-test.yml, .github/workflows/test-mindeps.yml, .github/workflows/test.yml
GitHub Actions doesn't show colour outputs for pytest by default (https://github.com/pytest-dev/pytest/issues/7443), but it can be enabled by setting a `--color=yes` flag.
| Before (black & white :panda_face:) | After (color :rainbow:) |
|--|--|
|![image](https://github.com/user-attachments/assets/c6a81191-1347-4c26-9e62-efb6c25cc484) | ![image](https://github.com/user-attachments/assets/d7c98961-65b2-45cb-87ee-b2a7a53377a5) |
Enables color output for pytest on:
- .github/workflows/integration-test.yml
- .github/workflows/test-mindeps.yml
- .github/workflows/test.yml
title such as "Add testing …
=> Run pytest with `--color=yes` on GitHub Actions

.github/workflows/integration-test-review.yml, .github/workflows/integration-test.yml
Yet another attempt to get auto-commenting on PRs to work.
Fixes #1005
----
📚 Documentation preview 📚: https://earthaccess--1006.org.readthedocs.build/en/1006/
=> Write PR comment when int. tests fail on insufficient perms

.github/ISSUE_TEMPLATE/bug.yml, CHANGELOG.md
Resolves #984 . This is a small update to the bug template to include a new triage label, and fixing the existing bug label to align with our label updates per #760. @mfisher87 also suggested updating other issue templates while I'm in here, but we only have this bug template along with a config.yml, which only points to Discussions or a blank issue. Lmk if I'm missing something here! 
- Links to any …
=> Update bug and triage label names in bug Issue template

.github/ISSUE_TEMPLATE/experience-report.yml, docs/quick-start.md
I have added a template for experience reports as well as a call for them in the quickstart guide, as discussed in the [issue](https://github.com/nsidc/earthaccess/issues/575). 
----
📚 Documentation preview 📚: https://earthaccess--1008.org.readthedocs.build/en/1008/
=> Added experience reports

.github/workflows/integration-test-review.yml
Hopefully this is the last fix to get PR comments to work. The workflow was attempting to unzip the pr_number.zip artifact at the wrong path, so was failing the workflow to add the PR comment.
These changes _should_ allow the unzip to work now, which should then allow the PR number to be read from the unzipped artifact, which should then allow a comment to be added to the PR.
----
📚 Documentation preview 📚: https://earthaccess--1013.org.readthedocs.build/en/1013/
=> Fix path to pr_number.zip artifact

CHANGELOG.md, earthaccess/exceptions.py, earthaccess/store.py
I have added the logic for handling download failure as discussed [here](https://github.com/nsidc/earthaccess/issues/996).  Also I observed that we have same block for Changed twice in CHANGELOG, is this done on purpose?
----
📚 Documentation preview 📚: https://earthaccess--1012.org.readthedocs.build/en/1012/
=> Add an exception `DownloadFailure` for handling failure.

.github/workflows/integration-test-review.yml
The auto-comment on PRs is now working! See #1013 for the fix, and #1012 for correctly added comments.
However within the auto-generated comment, the link on the text "code changes in this pull request" is broken, so it doesn't properly link to the files (diff) view of the PR.
This PR attempts to fix the broken link in the generated comment.
----
📚 Documentation preview 📚: https://earthaccess--1014.org.readthedocs.build/en/1014/
=> Fix link to PR files in PR auto-comment

CHANGELOG.md, earthaccess/search.py
I was tripped up by functions' docstrings suggesting the string to use as the "daac" argument for GESDISC should be "GESDISC" but it is actually set to "GES_DISC" in daac.py. This PR updates those docstrings.
[GitHub docs - Linking a pull request to an …
=> Update function docstrings with GES_DISC to match daac.py

CHANGELOG.md, docs/howto/authenticate.md, earthaccess/api.py, earthaccess/store.py
This is a minor patch to restore the progress bar when we open and download files, the default is to show it if we are in a notebook and there is a new parameter to mute it with `hide_progress` in both download() and open(). 
----
📚 Documentation preview 📚: https://earthaccess--1065.org.readthedocs.build/en/1065/
=> Show progress bar in interactive sessions (Jupyter, REPL) by default

CHANGELOG.md, earthaccess/results.py, tests/integration/test_api.py
Closes #970 
Simple fix to check for `FileDistributionInformation` existence before using it in the response. Id it does not exist, we return the empty string.
[GitHub docs - Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-a …
=> Fixed issue when `FileDistributionInformation` doesn't exist in a summary() call

earthaccess/search.py
This allows the `granule_name` parameter to be a list of strings, thereby allowing the search over multiple granule names (e.g. for ICESat-2 multiple RGTs). This works as `python_cmr` queries allow the [passing of lists](https://github.com/nasa/python_cmr/blob/35b8bdafa655c9a95edc41659ccb867df9e86c18/cmr/queries.py#L247-L250) when building the CMR query url.
- Links to any issues resolved by this PR …
=> allow `granule_name` to be `Iterable[str]`
