- README.md
- docs/index.md
- earthdata/accessor.py
- notebooks/Demo.ipynb
- tests/test_queries.py
> fix various typos

- .github/dependabot.yml
- .github/workflows/documentation.yml
- .github/workflows/test.yml
- CHANGELOG.md
- docs/css/styles.css
- docs/index.md
- docs/user-reference/collections/collections-query.md
- earthdata/auth.py
- earthdata/daac.py
- earthdata/formatters.py
- earthdata/results.py
- earthdata/search.py
- earthdata/store.py
- mkdocs.yml
- poetry.lock
- pyproject.toml
* docstrings are now following the google convention with mkdocstrings
* re-implemented base classes to update the docstrings format
* added types to method signatures
* Using `CMR-Search-After` see #145 
bug fixes:
* added GES_DISC missing S3 endpoint
* removed unnecessary print statements
> improve documentation in mkdocs,

- earthdata/daac.py
- earthdata/results.py
- earthdata/search.py
- earthdata/store.py
- poetry.lock
- pyproject.toml
- tests/test_store.py
Fixing things
* multidispatch with empty list was broken
* LPDAAC and GESDISC S3 were not working
> Preparing for v0.4.1

- README.md
Did this because red looks like fail :)
> LOVE the art badge! Changed color to blue @betolink

- CHANGELOG.md
Testing the new release workflow
> releasing v0.4.6

- earthaccess/api.py
Allow users to input the persist keyword from the api login function
> add persist kwarg to api login

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
This change will not affect PRs for security updates.
> Update dependabot to make one update PR per month

- .github/dependabot.yml
> Use dependabot to update Github Actions

- CHANGELOG.md
- CITATION.cff
- pyproject.toml
Closes https://github.com/nsidc/earthaccess/issues/404
> Release 0.8.2

- .pre-commit-config.yaml
- pyproject.toml
Addresses #788 
----
📚 Documentation preview 📚: https://earthaccess--793.org.readthedocs.build/en/793/
> Disable linting jupyter notebooks

- CHANGELOG.md
- docs/howto/search-granules.md
Resolves #779 
I've removed the broken link. Please take a look at it
----
📚 Documentation preview 📚: https://earthaccess--790.org.readthedocs.build/en/790/
> Removed broken link named introduction to nasa earthaccess

- CHANGELOG.md
- docs/user_guide/backwards-compatibility.md
- mkdocs.yml
Added the docs for backwards compatibility as per the issue descriptions. "resolves #471".
----
📚 Documentation preview 📚: https://earthaccess--763.org.readthedocs.build/en/763/
> Docs for backwards compatibility

- earthaccess/api.py
- uv.lock
See #833 for some context!
----
📚 Documentation preview 📚: https://earthaccess--835.org.readthedocs.build/en/835/
> Address some checks which failed after releasing

- .github/workflows/integration-test.yml
- .github/workflows/test.yml
It's been out for a month and community support is pretty broad -- if I create a new earthaccess env locally, I get python 3.13 now.
`## …
> add python 3.13 to our test matrices

- .github/workflows/discussions.yml
See #914!
Resolves #801 
----
📚 Documentation preview 📚: https://earthaccess--917.org.readthedocs.build/en/917/
> Fix `CATEGORY_ID` in hack day discussion workflow

- CODE_OF_CONDUCT.md
- docs/contributing/maintainers-guide.md
- docs/index.md
Content changes per NASA direction received on 1/22/2025, per Executive Order on 1/20/2025: https://www.whitehouse.gov/presidential-actions/2025/01/ending-radical-and-wasteful-government-dei-programs-and-preferencing/
----
📚 Documentation preview 📚: https://earthaccess--928.org.readthedocs.build/en/928/
> NASA directive updates

- earthaccess/store.py
- mkdocs.yml
The `rendering` key is no longer supported.
This was changed in v0.19.0 -- it seems the deprecation period ended in the latest release.
https://mkdocstrings.github.io/usage/handlers/?h=rendering#rendering-options
[GitHub docs - Linking a pull request to an …
> Fix RTD build by updating `mkdocstrings` config

- CHANGELOG.md
- CITATION.cff
- pyproject.toml
----
📚 Documentation preview 📚: https://earthaccess--951.org.readthedocs.build/en/951/
> Release v0.14.0

- CHANGELOG.md
- earthaccess/api.py
This PR addresses #602 which makes the `endpoint` argument of the `get_s3_filesystem` method in `api.py` available to the user.
* A new optional `endpoint` argument was added to `earthaccess.api.get_s3_filesystem`
* The logic used to identify the correct set of parameters that should be used in `earthaccess.__store__.get_s3_filesystem` was modified
* Error messages were added for invalid sets of arguments
```python
import earthaccess
earthaccess.get_s3_filesystem(endpoint="https://nisar.asf.earthdatacloud.nasa.gov/s3credentials")
```
title such as "Add testing details to the contributor section of …
> Expose the endpoint argument in earthaccess.get_s3fs_session

- .github/workflows/integration-test-review.yml
Fixes #922
----
📚 Documentation preview 📚: https://earthaccess--978.org.readthedocs.build/en/978/
> Add PR comment on insufficient test permissions

- CHANGELOG.md
- notebooks/Demo.ipynb
corrects typo "haromny" to "harmony" in markdown cell of notebooks/Demo.ipynb
- [x ] Please review our
- [x ] Populate a descriptive title. For example, instead of "Updated README.md", use a
- [x ] Populate the body of the pull request with:
[GitHub docs - Linking a pull request to an …
> Harmony typo corrected in markdown cell of  notebooks/Demo.ipynb

- CHANGELOG.md
- earthaccess/api.py
- earthaccess/store.py
I have added checks for the functions as discussed in the [issue](https://github.com/nsidc/earthaccess/issues/807). Please let me know about any problems with this implementation.
----
📚 Documentation preview 📚: https://earthaccess--1002.org.readthedocs.build/en/1002/
> Added checks for _get_granules and _get_urls which enables them to check for existing files.

- CITATION.cff
Thanks so much for your contributions, @Sherwin-14 :bow: 
[Common …
> Recognize Sherwin Varghese as an author

- docs/howto/authenticate.md
The second numbered item was not actually being rendered as a list …
> Separate numbered list of auth mechanisms

- CHANGELOG.md
- earthaccess/dmrpp_zarr.py
> fix virtualizarr imports

- CHANGELOG.md
- CITATION.cff
- pyproject.toml
- uv.lock
> bump version patch 0.15.1
